[project]
name = "actions"
version = "0.1.0"
description = "GitHub Actions test"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
actions = "actions:main"

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest==9.1.1",
    "ruff==0.16.4",
    "ty==0.0.74",
]

[tool.ruff.lint]
select = ["D", "F", "PL"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"
