name: learn-github-actions
run-name: Build and test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: astral/uv@sha256:dc360d7e5f968c682e8b59e83027a315a0232dead15cb9dfe3e707a12ba390e1
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up project
        run: uv sync --locked --all-extras --dev
      - name: Lint
        run: uv run ruff check
      - name: Format-check
        run: uv run ruff format --check
      - name: Type-check
        run: uv run ty check
  test:
    runs-on: ubuntu-latest
    container: astral/uv@sha256:dc360d7e5f968c682e8b59e83027a315a0232dead15cb9dfe3e707a12ba390e1
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up project
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run pytest
