name: Learn GitHub Actions
run-name: Lint and test
on: [ push ]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: astral/uv@sha256:b34a186d79e99aca2f5f143655cc750770a307da3167d5da625bfa8332a82b7d
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up project
        run: uv sync --locked --all-extras --dev
      - name: Lint
        run: uv run ruff check
      - name: Format-check
        run: uv run ruff format --check
      - name: Type-check
        run: uv run ty check
  test:
    runs-on: ubuntu-latest
    container: astral/uv@sha256:b34a186d79e99aca2f5f143655cc750770a307da3167d5da625bfa8332a82b7d
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up project
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run pytest
